class IW #(type T = int); typedef T same_t; endclass
class Deep #(
    type I0 = byte,
    type I1 = IW#(I0)::same_t,
    type I2 = IW#(I1)::same_t,
    type I3 = IW#(I2)::same_t,
    type I4 = IW#(I3)::same_t,
    type I5 = IW#(I4)::same_t,
    type I6 = IW#(I5)::same_t,
    type I7 = IW#(I6)::same_t,
    type I8 = IW#(I7)::same_t,
    type I9 = IW#(I8)::same_t,
    type I10 = IW#(I9)::same_t,
    type I11 = IW#(I10)::same_t,
    type I12 = IW#(I11)::same_t,
    type I13 = IW#(I12)::same_t,
    type I14 = IW#(I13)::same_t,
    type I15 = IW#(I14)::same_t,
    type I16 = IW#(I15)::same_t,
    type I17 = IW#(I16)::same_t,
    type I18 = IW#(I17)::same_t,
    type I19 = IW#(I18)::same_t,
    type I20 = IW#(I19)::same_t,
    type I21 = IW#(I20)::same_t,
    type I22 = IW#(I21)::same_t,
    type I23 = IW#(I22)::same_t,
    type I24 = IW#(I23)::same_t,
    type I25 = IW#(I24)::same_t,
    type I26 = IW#(I25)::same_t,
    type I27 = IW#(I26)::same_t,
    type I28 = IW#(I27)::same_t,
    type I29 = IW#(I28)::same_t,
    type I30 = IW#(I29)::same_t,
    type I31 = IW#(I30)::same_t,
    type I32 = IW#(I31)::same_t,
    type I33 = IW#(I32)::same_t,
    type I34 = IW#(I33)::same_t,
    type I35 = IW#(I34)::same_t,
    type I36 = IW#(I35)::same_t,
    type I37 = IW#(I36)::same_t,
    type I38 = IW#(I37)::same_t,
    type I39 = IW#(I38)::same_t,
    type I40 = IW#(I39)::same_t
);
  typedef I40 out_t;
endclass
module t; Deep#()::out_t x; initial if ($bits(x) != 8) $stop; endmodule
